name: build-publish-deploy

on: [push]

env:
  IMAGE: panda-adventure

jobs:
  build-publish-deploy:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Publish
        run: |-
          docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:$GITHUB_SHA"

      - name: Deploy
        run: |-
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --region ${{ secrets.GCP_REGION }} --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:$GITHUB_SHA"
